### ISSUE TITLE
kapitan source tarball on PyPI doesn't include requirements.txt

### ISSUE THREAD

**Issue by ifduyue** [deepmind/kapitan#188]
```
$ pip install --user kapitan
Collecting kapitan
  Downloading https://files.pythonhosted.org/packages/ac/01/613694f1f2eb99f73a6ea9ecc4e4d04492dc918048b438410c2faec88461/kapitan-0.21.0.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 617kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-exgfpmrk/kapitan/setup.py", line 55, in <module>
        pkgs, new_links = install_deps()
      File "/tmp/pip-install-exgfpmrk/kapitan/setup.py", line 41, in install_deps
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by adrianchifor** [comment]
Are you using python 3.6+? Also can you try adding `--no-cache` to install

**Comment by captn3m0** [comment]
Using no-cache doesn't work with `0.23.0`:

```
pip3 install --no-cache kapitan
Collecting kapitan
  Downloading https://files.pythonhosted.org/packages/ca/df/6e4c4e9dc1c905aa9a3297276297565a5c5044c441012949235979913913/kapitan-0.23.0.tar.gz (91kB)
     |████████████████████████████████| 92kB 513kB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-45zoj74h/kapitan/setup.py", line 55, in <module>
        pkgs, new_links = install_deps()
      File "/tmp/pip-install-45zoj74h/kapitan/setup.py", line 41, in install_deps
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-45zoj74h/kapitan/
```

```
Python: 3.7.3
Pip: 19.1
```

**Comment by captn3m0** [comment]
Forcing wheel install doesn't work either:

```
pip install --no-cache  --only-binary :all: kapitan
Collecting kapitan
  Downloading https://files.pythonhosted.org/packages/d9/fb/0b16f3d43ebdfac5d571eb4c2d8bf9b629288fcc01f9c0fa9e57f75c1f1b/kapitan-0.23.0-py3-none-any.whl (144kB)
     |████████████████████████████████| 153kB 797kB/s 
Collecting addict==2.2.0 (from kapitan)
  ERROR: Could not find a version that satisfies the requirement addict==2.2.0 (from kapitan) (from versions: none)
ERROR: No matching distribution found for addict==2.2.0 (from kapitan)
```

**Comment by ifduyue** [comment]
@captn3m0 try this: ``pip install --no-cache  --only-binary kapitan kapitan``

**Comment by captn3m0** [comment]
It works! Thanks.

I'll file a PR for the docs.
