### ISSUE TITLE
Docker test failing due to urllib version

### ISSUE THREAD

**Issue by yoshi-1224** [deepmind/kapitan#295]
**Describe the bug/feature**
When I run `make test`, the following error occurs.

```bash
----- Testing run of docker ci image -----
docker run -ti --rm kapitan-ci kapitan --help
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.2 (/usr/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.20; python_version >= "3.4"'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/kapitan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.2 (/usr/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.20; python_version >= "3.4"'), {'botocore'})
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 1
```

**To Reproduce**
Run `make test`

**Expected behavior**
Test should succeed without error.
 - `python --version`: 3.6.7
 - `pip3 --version`: 9.0.1
 - `Are you using pyenv or virtualenv?`: anaconda

**Additional context**
During the build, I get 
```bash
...
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517): started
  Building wheel for cryptography (PEP 517): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/43/61/c8/0a4464601ce180d26e0a8dfdfa88c824e419dcc65bd43bda6e
Successfully built cryptography
ERROR: botocore 1.12.150 has requirement urllib3<1.25,>=1.20; python_version >= "3.4", but you'll have urllib3 1.25.2 which is incompatible.
```
I'm guessing this is the cause. Here is an issue that is being created in botocore repository. https://github.com/boto/botocore/issues/1733

**Comment by uberspot** [comment]
Confirmed I get the same issue.

**Comment by yoshi-1224** [comment]
Shall we just change the requirement for `requests` from `requests>=2.21.0` to `requests==2.21.0`? Just tested this fixes the issue. 
What's causing this error is that `requests 2.22.0` released recently changed the requirement for `urllib` that conflicts with `botocore`.
