### ISSUE TITLE
Jsonnet input type cannot output a string

### ISSUE THREAD

**Issue by tprobinson** [deepmind/kapitan#431]
**Describe the bug/feature**
If a jsonnet component outputs a string instead of an object, Kapitan will crash during compilation:

```
Unknown (Non-Kapitan) Error occured
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing/pool.py", line 121, in worker
  File "kapitan/targets.py", line 387, in compile_target
  File "kapitan/inputs/base.py", line 59, in compile_obj
  File "kapitan/inputs/base.py", line 74, in compile_input_path
  File "kapitan/inputs/jsonnet.py", line 61, in compile_file
AttributeError: 'str' object has no attribute 'items'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kapitan/targets.py", line 95, in compile_targets
  File "kapitan/targets.py", line 95, in <listcomp>
  File "multiprocessing/pool.py", line 748, in next
AttributeError: 'str' object has no attribute 'items'

```

**To Reproduce**
1. Set up a test Kapitan project as follows:

`inventory/targets/test.yml`
```yaml
classes:
  - test

parameters:
  kapitan:
    vars:
      target: test
```

`inventory/classes/test.yml`
```yaml
parameters:
  kapitan:
    compile:
    - output_path: .
      input_type: jsonnet
      output_type: json
      input_paths:
        - components/test.jsonnet
```

`components/test.jsonnet`
```json
'test'
```

2. Run `kapitan compile`

**Expected behavior**
The output file contains a double-quoted string, which is valid JSON.

** If it's a bug (please complete the following information):**
 - `python --version`: Python 2.7.16
 - `pip3 --version`: Not installed.
 - `Are you using pyenv or virtualenv?`: Neither, using static kapitan binary on Ubuntu 19.10

**Comment by uberspot** [comment]
Fixed on master. Added a test + a small doc update for it as well.
We'll do another rc version within the week. :) 
Closing this for now.
