### ISSUE TITLE
Crash in subvar revealing in examples

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#499]
**Describe the bug/feature**
Crash when revealing subvars in examples
**To Reproduce**

```
cd examples/kubernetes/
kapitan compile --reveal     
Compiled busybox (0.12s)
Compiled minikube-nginx-kadet (0.15s)
Compiled minikube-nginx-jsonnet (0.24s)
Compiled labels (0.06s)
Compiled minikube-mysql (0.30s)
Compiled minikube-es (0.54s)
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/google/home/pawelsa/.pyenv/versions/3.7.1/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/targets.py", line 408, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/inputs/base.py", line 52, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/inputs/base.py", line 74, in compile_input_path
    **kwargs,
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/inputs/jsonnet.py", line 87, in compile_file
    fp.write_yaml(item_value)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/inputs/base.py", line 117, in write_yaml
    obj = self.revealer.reveal_obj(obj)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/refs/base.py", line 323, in reveal_obj
    obj[k] = self.reveal_obj(v)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/refs/base.py", line 323, in reveal_obj
    obj[k] = self.reveal_obj(v)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/refs/base.py", line 327, in reveal_obj
    obj = self.regex.sub(self._reveal_replace_match, obj)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/refs/base.py", line 246, in _reveal_replace_match
    return self._get_value_in_yaml_path(revealed_yaml, subvar_path)
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/refs/base.py", line 259, in _get_value_in_yaml_path
    value = value[key]
KeyError: 'var2'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/targets.py", line 92, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/google/home/pawelsa/.local/lib/python3.7/site-packages/kapitan/targets.py", line 92, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/google/home/pawelsa/.pyenv/versions/3.7.1/lib/python3.7/multiprocessing/pool.py", line 774, in next
    raise value
KeyError: 'var2'
'var2'
```

**Expected behavior**
No crash

Latest python and kapitan versions

**Comment by ramaro** [comment]
This is actually not a bug. What's happening here is that the ref file `refs/targets/all-glob/mysql/subvars` is missing the `var2` key.
But the error message needs to be improved.

**Comment by th31nitiate** [comment]
I noticed a similar thing too. Do you think this would be a good enough method for raising the error message ? 

    def _get_value_in_yaml_path(self, d, yaml_path):
        """using the sub-variable path as nested keys, returns the value in the dictionary"""
        keys = yaml_path.split(".")
        value = d
        try:
          for key in keys:
              value = value[key]
          return value
        except KeyError:
            raise RefError("Could not find referenced secret key: {}".format(key))


If so I can create a PR for it.

**Comment by ramaro** [comment]
Hey thanks for that but I already have a fix coming up!

**Comment by uberspot** [comment]
Fixed in https://github.com/deepmind/kapitan/pull/502
